### ISSUE TITLE
Inline JSON Report

### ISSUE THREAD

**Issue by smarlowucf** [numirias/pytest-json-report#11]
I created a PR in the [pytest-json](https://github.com/mattcl/pytest-json/pull/8) project which would allow the use of the plugin from code rather than saving to a file. Since that project is not maintained would there be interest and adding similar functionality to pytest-json-report?

This would be helpful when running pytest in code:

```
cmds = shlex.split(args)
plugin = JSONReport()
result = pytest.main(cmds, plugins=[plugin])
plugin.report # report dict
```

I can make a PR but wanted to gauge interest first.

**Comment by smarlowucf** [comment]
> Is there a technical advantage?

The specific use case is here https://github.com/SUSE/ipa/blob/master/ipa/ipa_provider.py#L295. And leverages a very simplified plugin https://github.com/SUSE/ipa/blob/master/ipa/results_plugin.py.

The goal to run multiple pytest sessions and aggregate the results into a dictionary without having to write/read from disk. Would like to leverage a more robust plugin for this but not sure a better way to access the results outside the realm of `conftest.py` hooks.

So from your first example I could do something like:

```
class MyPlugin:
    def pytest_json_modifyreport(self, json_report):
        self.report = json_report

plugin = MyPlugin()
pytest.main(['--json-report'], plugins=[plugin])
plugin.report
```

If so is it possible to prevent the pytest-json-report plugin from also writing the report to disk? Since the goal is to aggregate many session reports before persisting.

**Comment by numirias** [comment]
I was concerned it would be nasty to get a handle to `pytest.config` when using the plugin directly from code, but it's surprisingly straightforward. With the changes in #12 you should be able to use the plugin the way you planned.

> If so is it possible to prevent the `pytest-json-report` plugin from also writing the report to disk?

If you want I can add a switch, but writing to `/dev/null` seems conventional:

```python
import os

pytest.main(['--json-report', '--json-report-file', os.devnull], plugins=[plugin])
```
if that looks good to you, I'll merge the PR and make a new release.

**Comment by smarlowucf** [comment]
> If that looks good to you, I'll merge the PR and make a new release.

Yeah, that looks great, thanks! I think writing to /dev/null is sufficient.
