### ISSUE TITLE
SyntaxError: invalid syntax in line 175   =====**self.json_location(node), ====

### ISSUE THREAD

**Issue by shelderzhang** [numirias/pytest-json-report#14]
![image](https://user-images.githubusercontent.com/12554852/40735733-840c9f36-646e-11e8-9373-78ecf395dfd1.png)

**Comment by numirias** [comment]
As you can see in the README and on PyPI, the plugin is not available for the [soon to be retiring](https://pythonclock.org/) Python 2.
