### ISSUE TITLE
JSON report not produced on parallel tests running

### ISSUE THREAD

**Issue by rzegnam** [numirias/pytest-json-report#16]
Hi,
I've tried to use your tools with pytest-xdist but it seems that when running tests in parallel pytest-json-report is not working

pytest -v -n 2 [TEST_FOLDER] --json-report --json-report-file=report.json

**Comment by sosadchuk** [comment]
Had the same issue, created a fork which solved problems with pytest-xdist for me: https://github.com/sosadchuk/pytest-json-report

If it would help you also, I will add this as pull-request to initial pytest-json-report

**Comment by numirias** [comment]
@rzegnam I just published a refactored version of the plugin to PyPI which is tested on xdist. Do you mind verifying that the report is now produced as expected?
