### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by hexaclock** [numirias/pytest-json-report#23]
Not an issue, just wondering if you plan on creating a new PyPy release to include the recent features/changes? Thanks!

**Comment by numirias** [comment]
I'm currently in the middle of some major refactorings, so I'll defer official releases for now.

But I made a development pre-release that includes the latest changes. You can install it like this:

    pip install pytest-json-report==0.8.0.dev0 --upgrade --pre --no-cache-dir

**Comment by hexaclock** [comment]
Perfect, thank you!
