### ISSUE TITLE
Change value to --json-report-file dynamically during test set-up

### ISSUE THREAD

**Issue by swaingankar** [numirias/pytest-json-report#26]
I need to have the json report loaded to Elasticsearch and thus need to save the JSON with specific test run name, however this is not possible with the current option.

Can you please help

**Comment by swaingankar** [comment]
Thanks a lot for your response, will use the available hooks to get my problem resolved. 

Eagerly waiting for your next release, closing the issue.

**Comment by numirias** [comment]
Just to let you know, a new version has been released. (Be aware that there are some changes, such as minor adjustments in the JSON report format.)

I recommend the following to save your report to a custom path:
- Run pytest with `--json-report-file none`. This will keep the report from being saved automatically.
- Use a hook as follows:

```python
def pytest_sessionfinish(session):
    plugin = session.config._json_report
    plugin.save_report('/my/custom/path.json')
```

**Comment by swaingankar** [comment]
Hello,

Thanks a lot for such a quick turn-around, was away from my work, thus some delay in response.

Will test further and revert in case of any questions.
