### ISSUE TITLE
AttributeError: 'Function' object has no attribute '_json_report_extra'

### ISSUE THREAD

**Issue by sosadchuk** [numirias/pytest-json-report#29]
using pytest-json-report 1.0.1

test function:
```
def test_01_upload_ds(json_metadata):
```

getting error on test setup:
```
test setup failed
request = <SubRequest 'json_metadata' for <Function 'test_01_upload_ds'>>

    @pytest.fixture
    def json_metadata(request):
        """Fixture to add metadata to the current test item."""
>       return request.node._json_report_extra.setdefault('metadata', {})
E       AttributeError: 'Function' object has no attribute '_json_report_extra'

..\..\..\..\..\..\venv\lib\site-packages\pytest_jsonreport\plugin.py:254: AttributeError
```

pointed a debugger at:
```
@pytest.hookimpl(hookwrapper=True)
    def pytest_runtest_protocol(self, item, nextitem):
        item._json_report_extra = {}
        yield
        del item._json_report_extra
```
but never got there

**Comment by numirias** [comment]
Thanks for pointing that out! I can reproduce the issue and I'll look into it.

Weird that the corresponding tests are passing.

**Comment by numirias** [comment]
You most likely forgot to run pytest with `--json-report`. In that case, the metadata fixture is still found, but the plugin isn't actually run, so the required objects are unavailable.

I'll turn that into a more descriptive warning instead of this obscure error message.

@sosadchuk Can you confirm that the error disappears when running pytest with `--json-report`?

**Comment by numirias** [comment]
WIth [`v1.0.2`](https://github.com/numirias/pytest-json-report/releases/tag/v1.0.2), using the fixture now doesn't raise an error even without `--json-report`.

**Comment by sosadchuk** [comment]
actually we do use '--json-report ', but thx for the solution, all works good now
