### ISSUE TITLE
Rerun tests get reported as failures

### ISSUE THREAD

**Issue by jacebrowning** [numirias/pytest-json-report#31]
I am using https://github.com/box/flaky to attempt to rerun flaky tests. Here is some code that emulates flakiness:

```python
import pytest

FLAKY_RUNS = 0

@pytest.mark.flaky
def test_flaky_pass():
    assert 1 + 1 == 2

@pytest.mark.flaky
def test_flaky_fail():
    global FLAKY_RUNS
    FLAKY_RUNS += 1
    assert FLAKY_RUNS == 2
```

The `pytest` summary reports:

```text
=== 2 passed in 0.87 seconds ===
```

The https://github.com/pytest-dev/pytest-html report shows:

![](https://zappy.zapier.com/467009A8-6DF1-40C3-8FAC-B3C1747D3CDE.png)

But the JSON report from this library shows:

```json
{
  "created": 1549296205.722281,
  "duration": 0.8702988624572754,
  "exitcode": 0,
  },
  "summary": {
    "passed": 1,
    "failed": 1,
    "total": 2
  },
  "collectors": [
    { ...
```

How can I get `pytest-json-report` to treat the successfully rerun test as a pass?

**Comment by numirias** [comment]
Thanks for reporting. I'm afraid I need more information since your test case runs as expected for me locally and on Travis (see #33)

**Comment by jacebrowning** [comment]
I should have confirmed that on was on the latest version. 😄 

Upgrading from `0.7.0` to `1.0.2` fixes this!
