### ISSUE TITLE
summary showing xpassed test as passed

### ISSUE THREAD

**Issue by david-fliguer-ws** [numirias/pytest-json-report#39]
Hi, first of all kudos for this great plugin

I am running to the following file 

```
import pytest

def test_one():
    assert True

def test_two():
    assert False

@pytest.mark.skip
def test_three():
    assert True

@pytest.mark.xfail
def test_four():
    assert False

@pytest.mark.xfail
def test_five():
    assert True
```

But in the report, the summary shows

```
"summary": {
    "passed": 2,
    "failed": 1,
    "skipped": 1,
    "xfailed": 1,
    "num_tests": 5,
    "duration": 0.08672428131103516
}
```

seems that test_five is being counted as passed instead of xpassed

Is this a known issue ?

**Comment by numirias** [comment]
Your report is produced by [pytest-json](https://github.com/mattcl/pytest-json), another (unmaintained) plugin. My plugin produces the following summary for your test file in the latest version:

```
"summary": {
    "passed": 1,
    "failed": 1,
    "skipped": 1,
    "xfailed": 1,
    "xpassed": 1,
    "total": 5
}
```
