### ISSUE TITLE
Add additional fields to the report? 

### ISSUE THREAD

**Issue by jacebrowning** [numirias/pytest-json-report#4]
Is there any way to insert additional fields into each test's JSON object?

Specifically, I am capturing my own logs during each test and would like to make the path to each of these log files available in the report.

**Comment by numirias** [comment]
That's not currently possible but definitely a useful addition! Should be quick to implement, I'll let you know when it's done.

**Comment by numirias** [comment]
There is now a  `json_metadata` fixture to add metadata to the current test item, e.g.:
```python
def test_something(json_metadata):
    json_metadata['foo'] = {"some": "thing"}
```
The readme also lists [some other ways](https://github.com/numirias/pytest-json-report#metadata) to customize the report if you want to add more than just per-test metadata. Let me know if that works for you.

**Comment by jacebrowning** [comment]
I think `pytest_json_modifyreport` will do what I need. Thanks!

**Comment by jacebrowning** [comment]
This is working great!

My only complaint is that this large `metadata` block now appears in my test setup:

<a href="https://cl.ly/2x0b0o162U2I" target="_blank"><img src="https://s3.amazonaws.com/zapier-cloudapp/items/3b462Q1x3N0F0f2N0D2H/Screen%20Shot%202018-02-14%20at%208.31.10%20PM.png" style="display: block;height: auto;width: 100%;"/></a>

Did this plugin add that?

**Comment by numirias** [comment]
> Did this plugin add that?

No, that block is added by `pytest-metadata`, [right here](https://github.com/pytest-dev/pytest-metadata/blob/1363d9680c583d54d9a87b5d9fa5f48542f66a6c/pytest_metadata/plugin.py#L73). If you want an option to disable it, you might want to file an issue over there. :)

**Comment by jacebrowning** [comment]
FYI, clearing the metadata is as simple as:

```python
def pytest_configure(config):
    config._metadata.clear()
```

**Comment by numirias** [comment]
Yep, thanks, although I took your question more being about disabling the output in the terminal report, not removing metadata entirely. (I also had [submitted a patch](https://github.com/pytest-dev/pytest-metadata/issues/8) over there so that now metadata is only displayed in the terminal report if you use `--verbose`.)
