### ISSUE TITLE
The latest pytest 5.3.1 doesn't support pytest-json-report plugin

### ISSUE THREAD

**Issue by dkuchynskyi** [numirias/pytest-json-report#49]
The latest Pytest 5.3.1 doesn't support pytest-json-report plugin
here is link to the list of supported plugins from Pytest:
https://plugincompat.herokuapp.com/

![12333](https://user-images.githubusercontent.com/34566341/70427128-d892fd00-1a7c-11ea-81fb-36829cae4ab1.png)

**Comment by numirias** [comment]
Thanks for the heads-up! The plugincompat app currently tests against 5.2.4, not 5.3.1 though, right?

Anyway, as log message [it reports](https://plugincompat.herokuapp.com/output/pytest-json-report-1.2.1?py=py38&pytest=5.2.4):

```
tox run timed out

Time: 300.4 seconds
```

However, [on Travis the build passes](https://travis-ci.org/numirias/pytest-json-report/jobs/618868050) in under 2 minutes with pytest 5.3.1:

```
platform linux -- Python 3.8.0+, pytest-5.3.1, py-1.8.0, pluggy-0.13.1 -- /home/travis/build/numirias/pytest-json-report/.tox/py38/bin/python
```

Currently it seems the plugin works fine with latest pytest, but takes too long on plugincompat?

**Comment by dkuchynskyi** [comment]
I'm just trying to run my tests with json reporter, but the error appears:

ERROR: usage: pytest.py [options] [file_or_dir] [file_or_dir] [...]
pytest.py: error: unrecognized arguments: --json-report

Platform Win 10, python 3.8, Pytest 5.3.1
It works perfect with Pytest 5.2.2

**Comment by numirias** [comment]
If the `--json-report` flag is not recognized, the plugin is not installed/not found within your Python path. If you run pytest, it should show `pytest-json-report` in the plugin list, e.g.:

```
$ pytest
platform linux -- Python 3.8.0, pytest-5.3.1, py-1.8.0, pluggy-0.13.1
rootdir: ...
plugins: cov-2.8.1, requests-mock-1.7.0, metadata-1.8.0, json-report-1.2.1
collected 91 items
```

**Comment by dkuchynskyi** [comment]
I've installed it in pipenv instead of global installation in it works.
Thanks
