### ISSUE TITLE
AttributeError: 'TestReport' object has no attribute '_json_report_extra'

### ISSUE THREAD

**Issue by renlon** [numirias/pytest-json-report#51]
Encounter the following error when run pytest with pytest-xdist + pytest-json-report

Maybe this is more like a feature request. Or there is another way to run the test in xdist mode (multiple process in parallel) and get round this issue.

Here are the command options:
Pytest command options: ['--json-report', '--json-report-file=./test-report.json', '-s', 'test-integ/', '-n', '8', '--dist=loadfile', '--max-slave-restart=0']

Here is the error:
```
INTERNALERROR>   File "/lib/python3.7/site-packages/pytest_jsonreport/plugin.py", line 169, in pytest_runtest_logreport
INTERNALERROR>     metadata = report._json_report_extra.get('metadata')
INTERNALERROR> AttributeError: 'TestReport' object has no attribute '_json_report_extra'
```
Ptest-xdist 1.2.1
Python: 3.7
Pytest: 5.x
Pytest-json-report: latest

**Comment by Silipwn** [comment]
How to debug this? 

Having similar configuration with 
``` 
Python 3.7.9
pytest 6.2.2
pytest-xdist 2.1.1
pytest-json-report 1.2.4
```

**Comment by numirias** [comment]
@Silipwn Any chance you could give a reproducible example? Then I'm happy to take a look.

**Comment by Silipwn** [comment]
It actually worked out on a fresh install, I guess probably some cached package was causing the issue.
