### ISSUE TITLE
README.md: Direct invocation still creates a .report.json file

### ISSUE THREAD

**Issue by cornzyblack** [numirias/pytest-json-report#54]
### Direct invocation

You can also use the plugin when invoking `pytest.main()` directly from code:

```python
import pytest
from pytest_jsonreport.plugin import JSONReport

plugin = JSONReport()
pytest.main(['test_foo.py'], plugins=[plugin])

```
The above creates a default **.report.json** file which may not be expected.

To prevent the default **.report.json** file from being created, an optional argument can be passed, as shown in the following example:

```python
import pytest
from pytest_jsonreport.plugin import JSONReport

plugin = JSONReport()
pytest.main(['--json-report-file=none', 'test_foo.py'], plugins=[plugin])
```

**Comment by numirias** [comment]
Agree that this should be in the example, thanks!
