### ISSUE TITLE
can not use custom file name to store json report 

### ISSUE THREAD

**Issue by DigvijayPati** [numirias/pytest-json-report#56]
I am using following command to store report in given file in current directory. 
`python3  -m  pytest test.py --json-report-file=report.json` 
It does not create any file. But when I run following command
`python3 -m  pytest test.py --json-report`
It creates `.report.json` file in current directory.

**Comment by numirias** [comment]
The plugin only runs if `--json-report` is given. So, to create a report at a custom location, you need to use both flags:

    python3 -m pytest test.py --json-report --json-report-file=report.json
