### ISSUE TITLE
collect markers?

### ISSUE THREAD

**Issue by d-chambers** [numirias/pytest-json-report#71]
Hi,

First, great work on this plugin. We were using an older xml format and this has made things way nicer. 

I am looking for a way to add markers of each node into the report. Right now I have implemented this like so:

```python
def pytest_sessionfinish(session):
    """
    A hook called after running all tests and collecting results.
    """
    # Bail out early if we aren't generating the json report.
    if not session.config.getoption('json_report'):
        return
    # get the json report and add a dict of {marker_name: [node, ...]}
    report = session.config._json_report.report
    out = collections.defaultdict(list)
    for item in session.items:
        for marker in item.iter_markers():
            out[marker.name].append(item.nodeid)
    report['markers'] = dict(out)
```
but there is probably a better way. For me, it is important to collect markers for all tests, even the skipped ones. Would adding something about markers to the default output be worthwhile?

**Comment by d-chambers** [comment]
Ah, never mind. I see the markers are contained in the keywords of the test items. That is probably good enough.

**Comment by numirias** [comment]
Unless I had overlooked it back then, historically a node's markers were only provided as strings within the list of [`keywords`](https://docs.pytest.org/en/6.2.x/reference.html#pytest.nodes.Node.keywords).

Now that they are available as separate structures and easily iterable, there is a strong case for providing an explicit `markers` key in the JSON report. So thanks for pointing that out!
