### ISSUE TITLE
Conda forge version

### ISSUE THREAD

**Issue by d-chambers** [numirias/pytest-json-report#78]
Hello,

We are having issues building our conda packages because the version of pytest-json-report on conda-forge is so old. Do you mind taking a quick look at this PR:

https://github.com/conda-forge/pytest-json-report-feedstock/pull/6

If none of the pytest-json-report devs finds the conda packing very useful, I, or other ObsPy Devs, are happy to help out with that.

**Comment by megies** [comment]
Nothing that can be done from here I think @d-chambers, we just have to wait for a conda forge core member pushing that button over there since that feedstock is orphaned

**Comment by megies** [comment]
can be closed, conda forge feedstock has been updated
